### ISSUE TITLE
Order blueprint does not include region or country for Shipping address

### ISSUE THREAD

**Issue by sbrow** [damcclean/simple-commerce#1123]
### Description

Currently, by default, the shipping address for the order model does not contain a country or a region. 

### Steps to reproduce

https://github.com/duncanmcclean/simple-commerce/blob/cfea47131e1596431ce7d61e5eef0cea0662102b/resources/blueprints/collections/orders/orders.yaml#L287

### Environment

latest

**Comment by duncanmcclean** [comment]
That's odd. I certainly didn't intend to remove those fields.

I'll add them back when I get a chance.... or if someone beats me to it, I'd accept a PR.

**Comment by duncanmcclean** [comment]
I've fixed this for future installs. For existing sites, you'll need to add the fields manually:

```yaml
          - handle: shipping_region
            field:
              max_items: 1
              mode: default
              display: "Shipping Region"
              type: region
              icon: region
              width: 50
              listable: hidden
              visibility: read_only
          - handle: shipping_country
            field:
              max_items: 1
              mode: default
              display: "Shipping Country"
              type: country
              icon: country
              listable: hidden
              width: 50
              visibility: read_only
```
