### ISSUE TITLE
Values from `data` column in DB orders don't show on publish form

### ISSUE THREAD

**Issue by jacksleight** [damcclean/simple-commerce#1167]
### Description

We're storing orders in the database, and have a couple of custom fields in the order form. The values from these fields are saved successfully the `data` JSON column, but when you view the order in the CP the fields are blank.

Relevant blueprint fields:

```yaml
          -
            handle: data->where_did_you_hear_about_r_for_the_rest_of_us
            field:
              options:
                google-search: 'Google Search'
                social-media: 'Social Media'
                linkedin: LinkedIn
                friend-or-colleague: 'Friend or colleague'
                other: Other
              multiple: false
              clearable: false
              searchable: true
              taggable: false
              push_tags: false
              cast_booleans: false
              display: 'Where did you hear about R for the Rest of Us?'
              type: select
              icon: select
              listable: hidden
              instructions_position: above
              visibility: read_only
          -
            handle: data->where_did_you_hear_about_r_for_the_rest_of_us_other
            field:
              antlers: false
              display: 'Where did you hear about R for the Rest of Us? (Other)'
              type: textarea
              icon: textarea
              listable: hidden
              instructions_position: above
              visibility: read_only
              if:
                where_did_you_hear_about_r_for_the_rest_of_us: 'equals other'
          -
            handle: data->invoice_text
            field:
              antlers: false
              display: 'Invoice Text'
              type: textarea
              icon: textarea
              listable: hidden
              instructions_position: above
              visibility: read_only
          -
            handle: data->notes
            field:
              antlers: false
              display: Notes
              type: textarea
              icon: textarea
              instructions: 'This order note was entered by the customer at checkout.'
              listable: hidden
              instructions_position: above
              visibility: read_only
```

Example `data` column value:

```json
{
	"site": "default",
	"dummy": null,
	"notes": "Something something.",
	"status_log": [
		{
			"data": [],
			"status": "paid",
			"timestamp": 1727868005
		},
		{
			"data": [],
			"status": "placed",
			"timestamp": 1727868015
		}
	],
	"invoice_text": null,
	"where_did_you_hear_about_r_for_the_rest_of_us": "friend-or-colleague"
}
```

Form:

![Screenshot 2024-10-02 at 12 33 21](https://github.com/user-attachments/assets/ac6bbbf6-5d6c-4e14-bb14-332a8d5bc63a)

Additionally, the same values are blank in the API responses:

```json
    "where_did_you_hear_about_r_for_the_rest_of_us": {
      "value": null,
      "label": null,
      "key": null
    },
    "where_did_you_hear_about_r_for_the_rest_of_us_other": null,
    "invoice_text": null,
    "notes": null,
```

### Steps to reproduce

Store some custom values in the order `data` and add those fields to the order blueprint. 

### Environment

Environment
Application Name: rfortherestofus
Laravel Version: 11.23.5
PHP Version: 8.3.12
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: rfortherestofus.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Currencies: USD
Gateways: Dummy
Repository: Customer: DuncanMcClean\SimpleCommerce\Customers\UserCustomerRepository
Repository: Order: DuncanMcClean\SimpleCommerce\Orders\EloquentOrderRepository
Repository: Product: DuncanMcClean\SimpleCommerce\Products\EntryProductRepository
Shipping Methods
Tax Engine: DuncanMcClean\SimpleCommerce\Tax\BasicTaxEngine

Livewire
Livewire: v3.5.6

Statamic
Addons: 11
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.25.0 PRO

Statamic Addons
duncanmcclean/guest-entries: 4.0.1
duncanmcclean/simple-commerce: 7.5.0
jacksleight/statamic-bard-texstyle: 3.3.0
jacksleight/statamic-distill: 0.8.0
jonassiewertsen/statamic-livewire: 3.8.0
statamic-rad-pack/runway: 7.9.4
stillat/relationships: 2.2.1
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-commands: 3.2.0
studio1902/statamic-peak-seo: 7.5.0
studio1902/statamic-peak-tools: 4.4.2
