### ISSUE TITLE
Allow dynamic metadata

### ISSUE THREAD

**Issue by remiduval** [damcclean/simple-commerce#696]
### What would you like to see added?

Allow each product to define its own custom extra fields (metadata).
Currently, the Field Whitelist introduced in v3 makes it impossible to save them if they haven't been explicitly added to the config file beforehand.

### Is there a workaround you can use in the meantime?

On the front end, forcing the name attribute of the custom  fields's input to be "metadata_01", "metadata_02" etc and adding these names to the field whitelist beforehand.

### Priority wise - where's this feature for you?

Will need it in the next few weeks

**Comment by duncanmcclean** [comment]
Hey!

I've just taken a quick look into this and I think it would require a decent amount code to make wildcards work for this, unfortunately. 

One of the ways you could potentially get around this though is adding an array like `customer_input` to the field whitelist, then any inputs in the form in that array will be saved, no matter on the name.

So for example, you could do something like this:

```php
'line_items' => [
  'customer_input',
],
```

```antlers
<input type="text" name="customer_input[foo]">
<input type="text" name="customer_input[bar]">
<input type="text" name="customer_input[baz]">
```

This would however mean the data would end up being saved in an array in the line item metadata:

```yaml
items:
  -
    id: one
    product: two
    variant: null
    quantity: 1
    total: 1000
    tax: ...
    metadata:
      customer_input:
        foo: smth
        bar: smth
        baz: smth
```

Would something like that work for you? 

It's quite a lot of work otherwise to figure out the normal inputs that are allowed, then the wildcard ones and it gets messy if you try to nest stuff.. a whole can of worms 🪱
