### ISSUE TITLE
Redirect to cart after failed payment

### ISSUE THREAD

**Issue by benjibee** [damcclean/simple-commerce#762]
_This issue is connected to discussion #761_

#### What's happening

After a failed payment with Mollie, I'd like to redirect the user back to the `/checkout/payment` page with a flashed error message. Currently when the user returns from the failed payment, the cart is empty. The offsite checkout view that sends the user to Mollie has the following redirects:

```antlers
{{ sc:checkout:mollie redirect="/checkout/complete" error_redirect="/checkout/payment" }}
```

#### What's expected

The cart should be retained and an error message shown so that the user could select an alternate payment method.

### Steps to reproduce

1. Set the `error_redirect` route for Mollie as `/checkout/payment`
2. Checkout using Mollie
3. Select the payment status of `failed` on the Mollie test payment page
4. Be redirected back to `/cart` with the empty cart message being shown

### Environment

```yaml
Environment
Application Name: [removed]
Laravel Version: 9.40.1
PHP Version: 8.1.12
Composer Version: 2.4.4
Environment: production
Debug Mode: OFF
URL: [removed]
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Gateways: Banktransfer
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\EntryCustomerRepository
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EntryOrderRepository
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: [removed]
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\BasicTaxEngine

Statamic
Addons: 1
Antlers: regex
Version: 3.3.58 PRO

Statamic Addons
doublethreedigital/simple-commerce: 4.2.3
```
