### ISSUE TITLE
Product variant options - removing a variant option (e.g. Colors) merges the rest into one option - 4.1.3

### ISSUE THREAD

**Issue by paulweareframework** [damcclean/simple-commerce#831]
### Description

Hello,

The plugin is great and we love it and have used it on a couple of projects. But on one project it's recently started doing something different.

We've not had an issue for first 4/5 months but this week, when we try to click remove on a variant it does this (screenshots attached)
<img width="1419" alt="Screenshot 2023-02-24 at 11 39 36" src="https://user-images.githubusercontent.com/46562148/221194744-6aedb28b-dd90-4baf-861a-aefd2da06ba2.png">
<img width="1414" alt="Screenshot 2023-02-24 at 11 39 44" src="https://user-images.githubusercontent.com/46562148/221194750-dca27896-0b64-4952-8874-12fcefccfc43.png">
![Screenshot 2023-02-24 at 11 39 54](https://user-images.githubusercontent.com/46562148/221194752-bed33899-87a6-4e57-8d88-3060f1c42138.png)

I notice if you clear them out and input the options manually for product variants the value is not key: valued, they are 0: value
but our ones are like: key: value

We had recently upgraded to 4.1.3 (last week)

The values are imported not manually input, Might be we have been importing incorrectly this whole time and we need to re-do how we import it.

If any of how I've written this is not helpful, humble apologies and I can add and give anything you require if it helps.
Grateful for any time you get to look at this.

thank you
Paul

### Steps to reproduce

import to a product via import with the data in key value pairs e.g. We've been using our own plugin to do the import https://github.com/FrameworkDesign/api-product-importer
but the code maps like this:
```
$productVariantOptions = [];
$productVariantOptions[] = [
          'name' => 'colors'
          'values' => [['black_black' => 'black_black', 'grey_silver' => 'grey_silver']]
];

$productVariants = [
          'variants' => $variants, // this is looped through and put together in the codebase
          'options' => $productVariantOptions
];

// we've already found or made an $entry 
$entry->set('product_variants', $productVariants);
$entry->save();
```
the file that imports specifically:
https://github.com/FrameworkDesign/api-product-importer/blob/main/src/Jobs/Import/ImportConfigurableApiProductToStatamic.php#L127-L148

But once imported then editing in the cp panel for a product looks like this:
<img width="1419" alt="Screenshot 2023-02-24 at 11 39 36" src="https://user-images.githubusercontent.com/46562148/221199440-e8837afb-a648-497e-9a4a-7436006ecb40.png">

if we click to delete/remove one it then becomes this:
<img width="1414" alt="Screenshot 2023-02-24 at 11 39 44" src="https://user-images.githubusercontent.com/46562148/221199497-f1d21ce4-2701-408c-a618-3dd224f4817e.png">

### Environment

Environment
Application Name: Statamic
Laravel Version: 9.37.0
PHP Version: 8.1.16
Composer Version: 2.5.4
Environment: staging
Debug Mode: ENABLED
URL: rst-moto.whattheframework.uk/
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: postmark
Queue: database
Session: file

Simple Commerce
Gateways: Dummy
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\EntryCustomerRepository
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EntryOrderRepository
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Standard Post
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\Standard\TaxEngine

Statamic
Addons: 17
Antlers: runtime
Version: 3.3.37 PRO

Statamic Addons
doublethreedigital/duplicator: 2.3.2
doublethreedigital/simple-commerce: 4.1.3
jacksleight/statamic-bard-mutator: 1.1.2
jacksleight/statamic-bard-texstyle: 1.0.3
jonassiewertsen/statamic-jobs: 1.1.0
rias/statamic-data-import: 1.2.2
rias/statamic-link-it: 2.2.3
rias/statamic-redirect: 2.5.0
spatie/statamic-responsive-images: 2.14.2
statamic/seo-pro: 3.1.0
swiftmade/statamic-clear-assets: 1.1.0
weareframework/api-product-importer: dev-main
weareframework/clever-search: dev-main
weareframework/fwk-helper-tools: dev-develop
weareframework/fwk-responsive: dev-develop
weareframework/product-color-swatches: dev-main
webographen/statamic-admin-log: 1.0.6

**Comment by duncanmcclean** [comment]
Hey! A couple of questions:

1. After running the importer, what does the product variants look like in the YAML (inside an entry)?
2. v4.1.3 is quite an old version - have you tried updating to the latest release?

**Comment by paulweareframework** [comment]
Hello! 
thank you for the questions, so:

The yaml is like so:
```
product_variants:
  variants:
    -
      name: Colors
      values:
        black_black: black_black
        blue_silver_neon: blue_silver_neon
        blue_neon: blue_neon
    -
      name: Sizes
      values:
        8: '8'
        10: '10'
        12: '12'
        14: '14'
        16: '16'
        18: '18'
        20: '20'
  options:
    -
      sku: 102492_black_black_8
      color: black_black
      size: '8'
      size_uk: '8'
      size_intl: xs
      price: null
      key: 102492_black_black_8
      variant: 102492_black_black_8
    -
      sku: 102492_black_black_10
      color: black_black
      size: '10'
      size_uk: '10'
      size_intl: s
      price: null
      key: 102492_black_black_10
      variant: 102492_black_black_10
    -
      sku: 102492_black_black_12
      color: black_black
      size: '12'
      size_uk: '12'
      size_intl: m
      price: null
      key: 102492_black_black_12
      variant: 102492_black_black_12
    -
      sku: 102492_black_black_14
      color: black_black
      size: '14'
      size_uk: '14'
      size_intl: l
      price: null
      key: 102492_black_black_14
      variant: 102492_black_black_14
    -
      sku: 102492_black_black_16
      color: black_black
      size: '16'
      size_uk: '16'
      size_intl: xl
      price: null
      key: 102492_black_black_16
      variant: 102492_black_black_16
    -
      sku: 102492_black_black_18
      color: black_black
      size: '18'
      size_uk: '18'
      size_intl: 2xl
      price: null
      key: 102492_black_black_18
      variant: 102492_black_black_18
    -
      sku: 102492_black_black_20
      color: black_black
      size: '20'
      size_uk: '20'
      size_intl: 3xl
      price: null
      key: 102492_black_black_20
      variant: 102492_black_black_20
    -
      sku: 102492_blue_silver_neon_8
      color: blue_silver_neon
      size: '8'
      size_uk: '8'
      size_intl: xs
      price: null
      key: 102492_blue_silver_neon_8
      variant: 102492_blue_silver_neon_8
    -
      sku: 102492_blue_silver_neon_10
      color: blue_silver_neon
      size: '10'
      size_uk: '10'
      size_intl: s
      price: null
      key: 102492_blue_silver_neon_10
      variant: 102492_blue_silver_neon_10
    -
      sku: 102492_blue_silver_neon_12
      color: blue_silver_neon
      size: '12'
      size_uk: '12'
      size_intl: m
      price: null
      key: 102492_blue_silver_neon_12
      variant: 102492_blue_silver_neon_12
    -
      sku: 102492_blue_silver_neon_14
      color: blue_silver_neon
      size: '14'
      size_uk: '14'
      size_intl: l
      price: null
      key: 102492_blue_silver_neon_14
      variant: 102492_blue_silver_neon_14
    -
      sku: 102492_blue_silver_neon_16
      color: blue_silver_neon
      size: '16'
      size_uk: '16'
      size_intl: xl
      price: null
      key: 102492_blue_silver_neon_16
      variant: 102492_blue_silver_neon_16
    -
      sku: 102492_blue_silver_neon_18
      color: blue_silver_neon
      size: '18'
      size_uk: '18'
      size_intl: 2xl
      price: null
      key: 102492_blue_silver_neon_18
      variant: 102492_blue_silver_neon_18
    -
      sku: 102492_blue_silver_neon_20
      color: blue_silver_neon
      size: '20'
      size_uk: '20'
      size_intl: 3xl
      price: null
      key: 102492_blue_silver_neon_20
      variant: 102492_blue_silver_neon_20
    -
      sku: 102492_blue_neon_8
      color: blue_neon
      size: '8'
      size_uk: '8'
      size_intl: xs
      price: null
      key: 102492_blue_neon_8
      variant: 102492_blue_neon_8
    -
      sku: 102492_blue_neon_10
      color: blue_neon
      size: '10'
      size_uk: '10'
      size_intl: s
      price: null
      key: 102492_blue_neon_10
      variant: 102492_blue_neon_10
    -
      sku: 102492_blue_neon_12
      color: blue_neon
      size: '12'
      size_uk: '12'
      size_intl: m
      price: null
      key: 102492_blue_neon_12
      variant: 102492_blue_neon_12
    -
      sku: 102492_blue_neon_14
      color: blue_neon
      size: '14'
      size_uk: '14'
      size_intl: l
      price: null
      key: 102492_blue_neon_14
      variant: 102492_blue_neon_14
    -
      sku: 102492_blue_neon_16
      color: blue_neon
      size: '16'
      size_uk: '16'
      size_intl: xl
      price: null
      key: 102492_blue_neon_16
      variant: 102492_blue_neon_16
    -
      sku: 102492_blue_neon_18
      color: blue_neon
      size: '18'
      size_uk: '18'
      size_intl: 2xl
      price: null
      key: 102492_blue_neon_18
      variant: 102492_blue_neon_18
    -
      sku: 102492_blue_neon_20
      color: blue_neon
      size: '20'
      size_uk: '20'
      size_intl: 3xl
      price: null
      key: 102492_blue_neon_20
      variant: 102492_blue_neon_20
---

```


My bad, I for some reason thought it was latest and and you are right (out of date!)
Just going to try that

**Comment by duncanmcclean** [comment]
Thanks! I can reproduce the issue - it does indeed seem to be related to how the data is being formatted.

Would you be able to try switching the format of the `variants` array, like the example below? 

```yaml
product_variants:
  variants:
    -
      name: Colors
      values:
        - black_black
        - blue_silver_neon
        - blue_neon
    -
      name: Sizes
      values:
        - '8'
        - '10'
        - '12'
        - '14'
        - '16'
        - '18'
        - '20'
```

Essentially, the `values` for each variant shouldn't have keys, they should only be values.
